export enum Resource {
  USERS = 'users',
  ROLES = 'roles',
  PARTNERS = 'partners',
  SETTINGS = 'settings',
  PRODUCTS = 'products',
  PROJECT = 'project',
  ORDERS = 'orders',
  CAHIER_DES_CHARGES = 'cahier_des_charges',
  CDC_FILES = 'cdc_files',
  DEVIS = 'devis',
  INVENTORY = 'inventory',
  QUALITY = 'quality',
  PRODUCTION = 'production',
  LOGISTICS = 'logistics',
  HR = 'hr',
  FINANCE = 'finance',
  METHOD = 'method',
  AUDIT_LOGS = 'audit_logs',
  SESSIONS = 'sessions',
    RECLAMATIONS = 'reclamation',
  NOTIFICATIONS = 'notification',
  WORKFLOW_DISCUSSIONS = 'workflow_discussions',
  WORKFLOW_MESSAGES = 'workflow_messages',
  EMAIL='email',
}
